import { defineChimpbaseMigration } from "@chimpbase/core";

export default defineChimpbaseMigration({
  name: "001_init",
  sql: `CREATE TABLE IF NOT EXISTS factories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  manager_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP AS TEXT)
);

CREATE TABLE IF NOT EXISTS production_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factory_id INTEGER NOT NULL,
  product_sku TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'pending',
  priority TEXT NOT NULL DEFAULT 'normal',
  operator_email TEXT,
  started_at TEXT,
  completed_at TEXT,
  rejected_at TEXT,
  created_at TEXT NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP AS TEXT),
  updated_at TEXT NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP AS TEXT),
  FOREIGN KEY (factory_id) REFERENCES factories(id)
);

CREATE INDEX IF NOT EXISTS idx_orders_factory_status ON production_orders(factory_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_operator_status ON production_orders(operator_email, status);
CREATE INDEX IF NOT EXISTS idx_orders_sku ON production_orders(product_sku);

CREATE TABLE IF NOT EXISTS order_audit_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  order_id INTEGER NOT NULL,
  factory_code TEXT NOT NULL,
  product_sku TEXT NOT NULL,
  status TEXT NOT NULL,
  operator_email TEXT,
  created_at TEXT NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP AS TEXT)
);

CREATE INDEX IF NOT EXISTS idx_order_audit_log_order_id ON order_audit_log(order_id);

CREATE TABLE IF NOT EXISTS order_notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  queue_name TEXT NOT NULL,
  order_id INTEGER NOT NULL,
  factory_code TEXT NOT NULL,
  product_sku TEXT NOT NULL,
  recipient_email TEXT,
  sender_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CAST(CURRENT_TIMESTAMP AS TEXT)
);

CREATE INDEX IF NOT EXISTS idx_order_notifications_order_id ON order_notifications(order_id);
`,
});
